// <auto-generated />
using ComprasNerd.ProdutoAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComprasNerd.ProdutoAPI.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20220121150139_addprodutosTabela")]
    partial class addprodutosTabela
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ComprasNerd.ProdutoAPI.Model.Produto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("preco");

                    b.Property<string>("UrlImagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("url_imagem");

                    b.HasKey("Id");

                    b.ToTable("produto");

                    b.HasData(
                        new
                        {
                            Id = 5L,
                            Categoria = "Camiseta",
                            Descricao = "Teste de inserção via OnModelCreating",
                            Nome = "Nome",
                            Preco = 69.9m,
                            UrlImagem = "https://github.com/joaquimsimao/sgc_ecomerce/blob/master/SGC_e-comerce/ShoppingImages/00_no_image.jpg"
                        },
                        new
                        {
                            Id = 6L,
                            Categoria = "Camiseta",
                            Descricao = "Teste de inserção via OnModelCreating 2",
                            Nome = "Nome",
                            Preco = 40.9m,
                            UrlImagem = "https://github.com/joaquimsimao/sgc_ecomerce/blob/master/SGC_e-comerce/ShoppingImages/10_milennium_falcon.jpg"
                        },
                        new
                        {
                            Id = 7L,
                            Categoria = "Camiseta",
                            Descricao = "Teste de inserção via OnModelCreating 3",
                            Nome = "Nome",
                            Preco = 80.9m,
                            UrlImagem = "https://github.com/joaquimsimao/sgc_ecomerce/blob/master/SGC_e-comerce/ShoppingImages/11_mars.jpg"
                        },
                        new
                        {
                            Id = 8L,
                            Categoria = "Camiseta",
                            Descricao = "Teste de inserção via OnModelCreating 4",
                            Nome = "Nome",
                            Preco = 10.9m,
                            UrlImagem = "https://github.com/joaquimsimao/sgc_ecomerce/blob/master/SGC_e-comerce/ShoppingImages/12_gnu_linux.jpg"
                        },
                        new
                        {
                            Id = 9L,
                            Categoria = "Camiseta",
                            Descricao = "Teste de inserção via OnModelCreating 5",
                            Nome = "Nome",
                            Preco = 180.9m,
                            UrlImagem = "https://github.com/joaquimsimao/sgc_ecomerce/blob/master/SGC_e-comerce/ShoppingImages/13_dragon_ball.jpg"
                        },
                        new
                        {
                            Id = 10L,
                            Categoria = "Camiseta",
                            Descricao = "Teste de inserção via OnModelCreating 6",
                            Nome = "Nome",
                            Preco = 325.9m,
                            UrlImagem = "https://github.com/joaquimsimao/sgc_ecomerce/blob/master/SGC_e-comerce/ShoppingImages/14_patch_nasa.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
